application: web-central
version: 1

runtime: python27
api_version: 1
threadsafe: true

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs
  url_blacklist:

#default_expiration: "1d"
handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /web/(.*\.png)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.png)


- url: /web/(.*\.gif)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.gif)

- url: /web/(.*\.ico)
  static_files: build/static/\1
  expiration: 7d
  upload: build/static/(.*\.ico)

- url: /web/(.*\.jpg)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.jpg)

- url: /web/(.*\.woff)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.woff)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/(.*\.eot)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.eot)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/(.*\.ttf)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.ttf)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/(.*\.svg)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.svg)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/index.html
  static_files: build/static/fundamentals/index.html
  upload: build/static/fundamentals/index.html
  secure: always

- url: /web/
  static_files: build/static/index.html
  upload: build/static/index.html
  secure: always

- url: /web/(.+)/
  static_files: build/static/\1/index.html
  upload: build/static/(.+)/index.html
  secure: always

- url: /web/(.*)
  static_files: build/static/\1
  expiration:  1h
  upload: build/static/(.+)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

skip_files:
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.pxm$
