application: web-central
version: 1

runtime: python27
api_version: 1
threadsafe: true

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs
  url_blacklist:

#default_expiration: "1d"
handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /web/(.*\.png)
  static_files: build/static/_langs/en/\1
  expiration: 1d
  upload: build/static/_langs/en/(.*\.png)

- url: /web/imgs/(.*\.png)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.png)

- url: /web/(.*\.gif)
  static_files: build/static/_langs/en/\1
  expiration: 1d
  upload: build/static/_langs/en/(.*\.gif)

- url: /web/(.*\.ico)
  static_files: build/static/_langs/en/\1
  expiration: 7d
  upload: build/static/_langs/en/(.*\.ico)

- url: /web/fundamentals/imgs/(.*\.jpg)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.jpg)

- url: /web/(.*\.jpg)
  static_files: build/static/_langs/en/\1
  expiration: 1d
  upload: build/static/_langs/en/(.*\.jpg)

- url: /web/(.*\.svg)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.svg)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/(.*\.woff)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.woff)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/(.*\.eot)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.eot)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/(.*\.ttf)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.ttf)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com



- url: /web/(.*\.css)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.css)
  http_headers:
    Access-Control-Allow-Origin: https://developers.google.com

- url: /web/index.html
  script: main.app
  secure: always

- url: /web/
  script: main.app
  secure: always

- url: /web/(.*)
  script: main.app
  secure: always

skip_files:
- ^(.*/)?.*\.psd$
- ^(.*/)?.*\.pxm$
