application: web-central
version: CHANGEME
# NOTE: URL is CHANGEME.web-central.appspot.com
#       To specify a name, change 'CHANGEME' to something
#       like 'prod-zone-article'.
#

runtime: python27
api_version: 1
threadsafe: true

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs
  url_blacklist:
    - http://www.dartlang.org/*/code/out/*
    - https://www.dartlang.org/*/code/out/*

#default_expiration: "1d"

- url: /(.*\.png)
  static_files: static/\1
  expiration: 1d
  upload: static/(.*\.png)

- url: /(.*\.ico)
  static_files: static/\1
  expiration: 7d
  upload: static/(.*\.ico)

- url: /(.*\.jpg)
  static_files: static/\1
  expiration: 1d
  upload: static/(.*\.jpg)

- url: /(.*\.woff)
  static_files: static/\1
  expiration: 7d
  upload: static/(.*\.woff)

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html
  secure: always

- url: (.*\..*)
  static_files: static\1
  upload: static
  secure: always

