application: web-central
version: 1

runtime: python27
api_version: 1
threadsafe: true

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs
  url_blacklist:

#default_expiration: "1d"
handlers:
- url: /(.*\.png)
  static_files: static/\1
  expiration: 1d
  upload: static/(.*\.png)

- url: /(.*\.ico)
  static_files: static/\1
  expiration: 7d
  upload: static/(.*\.ico)

- url: /(.*\.jpg)
  static_files: static/\1
  expiration: 1d
  upload: static/(.*\.jpg)

- url: /(.*\.woff)
  static_files: static/\1
  expiration: 7d
  upload: static/(.*\.woff)

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html
  secure: always

- url: (.*\..*)
  static_files: static\1
  upload: static
  secure: always
