application: web-central
version: 1

runtime: python27
api_version: 1
threadsafe: true

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs
  url_blacklist:

#default_expiration: "1d"
handlers:
- url: /(.*\.png)
  static_files: ../../build/static/\1
  expiration: 1d
  upload: ../../build/static/(.*\.png)

- url: /(.*\.ico)
  static_files: ../../build/static/\1
  expiration: 7d
  upload: ../../build/static/(.*\.ico)

- url: /(.*\.jpg)
  static_files: ../../build/static/\1
  expiration: 1d
  upload: ../../build/static/(.*\.jpg)

- url: /(.*\.woff)
  static_files: ../../build/static/\1
  expiration: 7d
  upload: ../../build/static/(.*\.woff)

- url: /index.html
  static_files: ../../build/static/index.html
  upload: ../../build/static/index.html
  secure: always

- url: /
  static_files: ../../build/static/index.html
  upload: ../../build/static/index.html
  secure: always

- url: /(.*)
  static_files: ../../build/static/\1/index.html
  upload: ../../build/static/(.*)/index.html
  secure: always

- url: /(.*)
  static_files: ../../build/static/\1
  expiration: 7d
  upload: ../../build/static/(.*) 
