application: web-central
version: 1

runtime: python27
api_version: 1
threadsafe: true

pagespeed:
  enabled_rewriters:
    - InlineImages
    - CollapseWhitespace
    - RemoveComments
    - InlineJs
  url_blacklist:

#default_expiration: "1d"
handlers:
- url: /web/essentials/(.*\.png)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.png)

- url: /web/essentials/(.*\.ico)
  static_files: build/static/\1
  expiration: 7d
  upload: build/static/(.*\.ico)

- url: /web/essentials/(.*\.jpg)
  static_files: build/static/\1
  expiration: 1d
  upload: build/static/(.*\.jpg)

- url: /web/essentials/(.*\.woff)
  static_files: build/static/\1
  expiration: 7d
  upload: build/static/(.*\.woff)

- url: /web/essentials/index.html
  static_files: build/static/index.html
  upload: build/static/index.html
  secure: always

- url: /web/essentials/
  static_files: build/static/index.html
  upload: build/static/index.html
  secure: always

- url: /web/essentials/(.+)/
  static_files: build/static/\1/index.html
  upload: build/static/(.+)/index.html
  secure: always

- url: /web/essentials/(.*)
  static_files: build/static/\1
  expiration: 7d
  upload: build/static/(.+) 
