sudo: false
language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - vendor/bundle
    - node_modules
install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install -g gulp
  - npm install
  - git submodule init
  - git submodule update
script:
  - gulp build:staging
after_success:
  - tools/auto-deploy.sh
