sudo: false
language: ruby
node_js:
  - "0.12"
cache:
  directories:
    - vendor/bundle
    - node_modules
install:
  - bundle install --deployment --jobs=3 --retry=3
  - npm install -g gulp
  - npm install
script:
  - gulp build
after_success:
  - tools/auto-deploy.sh
