# For AppEngine
safe: false
port: 8081
source: src
destination: appengine/build/devsite
markdown: kramdown
permalink: /articles/:title.html
baseurl: /web
fundamentals: /web/fundamentals
url: /web
highlighter: pygments
spotlights: false
github:
  root: https://github.com/Google/WebFundamentals
  content: tree/master/src
include_open_html: true
custom:
kramdown:
  toc_levels: "2"
  entity_output: :as_input
include: ['.htaccess']
exclude: ['config.rb']
keep_files: ['_langs\/[a-z\-]+']
# comment this for plain jekyll serve usage.
langs_available: ['ar', 'de', 'es', 'fr', 'he', 'it', 'ja', 'ko', 'nl', 'pl', 'pt-br', 'ru', 'tr', 'zh-cn', 'zh-tw']
# primary language, source of translations.
prime_lang: en
sample_link_base: "/web/fundamentals/resources/samples/"
