safe: false
port: 8081
source: site
destination: appengine/build/static
markdown: kramdown
permalink: /articles/:title.html
baseurl: http://localhost:8081
url: http://localhost:8081
highlighter: pygments
pygments: false
spotlights: false
include_open_html: true
custom:
kramdown:
  toc_levels: "2"
include: ['.htaccess']
exclude: ['config.rb']
