safe: false
port: 8081
source: .
destination: ../appengine/build/static
markdown: kramdown
permalink: /articles/:title.html
pygments: false
custom:
kramdown:
  toc_levels: "2"
include: ['.htaccess']
exclude: ['config.rb']
