safe: false
port: 8081
source: .
destination: ../appengine/build/static
markdown: kramdown
permalink: /articles/:title.html
baseurl: /web/essentials
url: /web/essentials
pygments: false
custom:
kramdown:
  toc_levels: "2,3,4"
include: ['.htaccess']
exclude: ['config.rb']
